# Generated by Django 2.0.1 on 2019-01-27 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('linenos', models.BooleanField(default=False)),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('listed_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product_description', models.CharField(blank=True, default='', max_length=1500)),
                ('product_type', models.CharField(choices=[('a', 'art'), ('b', 'bracelet'), ('w', 'watch'), ('t', 'tech')], max_length=100)),
                ('is_stocked', models.BooleanField(default=True)),
                ('is_flash_sale', models.BooleanField(default=False)),
                ('highlighted', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
